config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :maintenance_items
  # if user is not an admin, going to /admins will give 404 error
  authenticated :user, -> (user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/users'
    get 'admin/transactions'
    patch 'admin/users/:id', to: 'admin#update', as: 'admin/user'
    get 'items/index', as: :admin_items
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # root to: "items#index"
  root to: 'items#member_items'

  put 'items/:id/checkout', to: 'items#checkout', as: 'checkout_item'

  get '/items/export', to:'items#export'
  post 'items/import', to: 'items#import', as: 'import_items'

  resources :items, except: [:index] do
    member do
      get :delete
      put 'checkout'
      get 'checkout'
      #post :button_action
    end
  end

  put 'transactions/:id/approve', to: 'transactions#approve', as: 'approve_transaction'

  resources :transactions do
    member do
      get :delete
      put 'approve'
      get 'approve'
    end
  end

  get 'member-items', to: 'items#member_items'
  get 'transactions', to: 'transactions#index'
end

app/models/maintenance_item.rb
class MaintenanceItem < ApplicationRecord
    validates :item_name, :description, :total_amount, :available_amount, presence: true
end

app/controllers/maintenance_items_controller.rb
class MaintenanceItemsController < ApplicationController
  before_action :set_maintenance_item, only: %i[ show edit update destroy ]

  # GET /maintenance_items or /maintenance_items.json
  def index
    @maintenance_items = MaintenanceItem.all
  end

  # GET /maintenance_items/1 or /maintenance_items/1.json
  def show
    @maintenance_item = MaintenanceItem.find(params[:id])
  end

  # GET /maintenance_items/new
  def new
    @maintenance_item = MaintenanceItem.new
  end

  # GET /maintenance_items/1/edit
  def edit
    @maintenance_item = MaintenanceItem.find(params[:id])
  end

  # POST /maintenance_items or /maintenance_items.json
  def create
    @maintenance_item = MaintenanceItem.new(maintenance_item_params)

    respond_to do |format|
      if @maintenance_item.save
        format.html { redirect_to maintenance_item_url(@maintenance_item), notice: "Maintenance item was successfully created." }
        format.json { render :show, status: :created, location: @maintenance_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance_items/1 or /maintenance_items/1.json
  def update
    respond_to do |format|
      if @maintenance_item.update(maintenance_item_params)
        format.html { redirect_to maintenance_item_url(@maintenance_item), notice: "Maintenance item was successfully updated." }
        format.json { render :show, status: :ok, location: @maintenance_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance_items/1 or /maintenance_items/1.json
  def destroy
    @maintenance_item.destroy

    respond_to do |format|
      format.html { redirect_to maintenance_items_url, notice: "Maintenance item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_item
      @maintenance_item = MaintenanceItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_item_params
      params.require(:maintenance_item).permit(:item_name, :description, :total_amount, :available_amount)
    end
end

app/helpers/maintenance_items_helper.rb
module MaintenanceItemsHelper
end

app/views/maintenance_items/_form.html.erb
<%= form_with(model: maintenance_item) do |form| %>
  <% if maintenance_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(maintenance_item.errors.count, "error") %> prohibited this maintenance_item from being saved:</h2>

      <ul>
        <% maintenance_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_name, style: "display: block" %>
    <%= form.text_field :item_name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :total_amount, style: "display: block" %>
    <%= form.number_field :total_amount %>
  </div>

  <div>
    <%= form.label :available_amount, style: "display: block" %>
    <%= form.number_field :available_amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/maintenance_items/_maintenance_item.html.erb
<div id="<%= dom_id maintenance_item %>">
  <p>
    <strong>Item name:</strong>
    <%= maintenance_item.item_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= maintenance_item.description %>
  </p>

  <p>
    <strong>Total amount:</strong>
    <%= maintenance_item.total_amount %>
  </p>

  <p>
    <strong>Available amount:</strong>
    <%= maintenance_item.available_amount %>
  </p>

</div>

app/views/maintenance_items/edit.html.erb
<h1>Editing maintenance item</h1>

<%= render "form", maintenance_item: @maintenance_item %>

<br>

<div>
  <%= link_to "Show this maintenance item", @maintenance_item %> |
  <%= link_to "Back to maintenance items", maintenance_items_path %>
</div>

app/views/maintenance_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Maintenance items</h1>

<div id="maintenance_items">
  <% @maintenance_items.each do |maintenance_item| %>
    <%= render maintenance_item %>
    <p>
      <%= link_to "Show this maintenance item", maintenance_item %>
    </p>
  <% end %>
</div>

<%= link_to "New maintenance item", new_maintenance_item_path %>

app/views/maintenance_items/new.html.erb
<h1>New maintenance item</h1>

<%= render "form", maintenance_item: @maintenance_item %>

<br>

<div>
  <%= link_to "Back to maintenance items", maintenance_items_path %>
</div>

app/views/maintenance_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @maintenance_item %>

<div>
  <%= link_to "Edit this maintenance item", edit_maintenance_item_path(@maintenance_item) %> |
  <%= link_to "Back to maintenance items", maintenance_items_path %>

  <%= button_to "Destroy this maintenance item", @maintenance_item, method: :delete %>
</div>