config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :maintenance_items
  # if user is not an admin, going to /admins will give 404 error
  authenticated :user, -> (user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/users'
    get 'admin/transactions'
    patch 'admin/users/:id', to: 'admin#update', as: 'admin/user'
    get 'items/index', as: :admin_items
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # root to: "items#index"
  root to: 'items#member_items'

  put 'items/:id/checkout', to: 'items#checkout', as: 'checkout_item'

  get '/items/export', to:'items#export'
  post 'items/import', to: 'items#import', as: 'import_items'

  resources :items, except: [:index] do
    member do
      get :delete
      put 'checkout'
      get 'checkout'
      #post :button_action
    end
  end

  put 'transactions/:id/approve', to: 'transactions#approve', as: 'approve_transaction'

  resources :transactions do
    member do
      get :delete
      put 'approve'
      get 'approve'
    end
  end

  get 'member-items', to: 'items#member_items'
  get 'transactions', to: 'transactions#index'
end

app/models/item.rb
require 'csv'

class Item < ApplicationRecord
    validates :name, :description, :serial_number, presence: true
    #available column can how hold true and false values
    validates :available, inclusion: { in: [true, false] }
  
    def self.to_csv
      attributes = %w{id name description serial_number available} # Specify the fields you want to export
      CSV.generate(headers: true) do |csv|
        csv << attributes
  
        all.each do |item|
          csv << attributes.map{ |attr| item.send(attr) }
        end 
      end
    end
    # change to has_many_atached if you want to attach multiple images
    has_one_attached :image, :dependent => :destroy

    # for search functionality
    #name ILIKE --> allows the SQL to match without being case sensitive
    scope :search, -> (term) { where('name ILIKE ?', "%#{term}%") if term.present? }
  end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # Display all items
  def index
    #Search Functionality
    #If search is empty, return all items
    #Else, return items that contain the search string
    @items = Item.search(params[:search])
  end

  # Show details of a specific item
  def show
    @item = Item.find(params[:id])
  end

  # Initialize a new item instance for form rendering
  def new
    @item = Item.new
  end

  # Form for editing an item
  def edit
    @item = Item.find(params[:id])
  end

  # Create a new item record
  def create
    @item = Item.new(item_params)
    @item.available = true

    # If there are existing items, set the new item ID to the next number.
    # Otherwise, set the ID to 1 for the first item.
    if Item.count != 0
      count = Item.last.id + 1
      @item.id = count
    else
      @item.id = 1
    end

    # Save the new item and redirect or render errors as necessary
    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
        flash[:notice] = "Successfully created item"
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # Update an item's details
  def update
  end


  # Confirm deletion of an item
  def delete
    @item = Item.find(params[:id])
  end

  # Remove an item from the database
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully removed." }
      format.json { head :no_content }
    end
  end

  def checkout
    @item = Item.find(params[:id])

    if @item.available
      # Mark the item as unavailable
      @item.update_attribute(:available, false)

      # Create a new Transaction entry with the item's serial_number
      Transaction.create(email: current_user.email, serial_number: @item.serial_number)

      redirect_to items_path, notice: "Item checked out and transaction created."
    else
      redirect_to items_path, alert: "Item is already checked out."
    end
  end

  # Display all items that are available
  def member_items
    #Search Functionality
    #If search is empty, return all items with available set to True (This is the case for member inventory)
    #Otherwise, only return items that contains the search string and is available
    @items = Item.search(params[:search]).where(available: true)
  end

  def export
    @items = Item.all

    # respond_to do |format|
    #   format.csv {send_data @items.to_csv, filename: "items-#{Date.today}.csv"}
    # end
    send_data @items.to_csv, filename: "items-#{Date.today}.csv"
  end

  def import
    if params[:file].present?
      csv_text = File.read(params[:file].path)
      csv = CSV.parse(csv_text, headers: true)
      csv.each do |row|
        item_hash = row.to_hash
        item_hash["available"] = case item_hash["available"].downcase.strip
                                 when 'true', 't', '1'
                                   true
                                 else
                                   false # Default value when it's not explicitly true.
                                 end
        
        item = Item.find_or_create_by(id: item_hash["id"])
        item.update!(item_hash)
      end

      redirect_to items_path, notice: "Items imported successfully!"
    else
      redirect_to items_path, alert: "Please upload a CSV file."
    end
  rescue ActiveRecord::RecordInvalid => e
    redirect_to items_path, alert: "There was an issue with importing items. Error: #{e.message}"
  end

  private

    # Strong parameters for item to prevent mass-assignment vulnerabilities
    def item_params
      params.require(:item).permit(:name, :serial_number, :description, :image, :available)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
    <%= form.label :serial_number,  style: "display: block"%>
    <%= form.text_field :serial_number %>
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %> <br>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class="card">
    <div class="card-header">
        <%= item.name %>
    </div>
    <div class="card-body">
        <table class="table table-sm">
            <thead>
            <tr>
                <th colspan="2"><%= item.name %></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>Serial Number</strong></td>
                <td><%= item.serial_number %></td>
            </tr>
            <% if current_user.admin? %>
                <tr>
                    <td><strong>Internal ID</strong></td>
                    <td><%= item.id %></td>
                </tr>
                <tr>
                    <td><strong>Available?</strong></td>
                    <td><%= item.available ? 'Yes' : 'No' %></td>
                </tr>
            <% end %>
            <tr>
                <td colspan="2">
                    <% if item.image.attached? %>
                        <%= image_tag item.image, class: "img-fluid mx-auto d-block" %>
                    <% else %>
                        <%# Placeholder image for testing purposes %>
                        <%= image_tag "placeholderRadio.png", size: "25x", class: "mx-auto d-block" %>
                    <% end %>
                </td>
            </tr>
        </tbody>
        </table>
    </div>
    <div class="card-footer text-center">
        <% if current_user.admin? %>
            <%= link_to "Edit", edit_item_path(item), class: "btn btn-info btn-sm" %>
            <%= link_to "Delete", delete_item_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
        <% end %>
        <%= link_to 'Checkout', checkout_item_path(item), method: :put, class: "btn btn-success btn-sm" %>
    </div>
</div>

app/views/items/delete.html.erb
<%= link_to("Back to Inventory", items_path, class: 'back-link') %>

<div class="items delete">
  <h2>Delete Item</h2>

  <%= form_for(@item, method: 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this item?</p>
    <p><%= @item.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Item") %>
    </div>

  <% end %>
</div>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing Item </h1>
  <%= render 'form', item: @item %>
  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>
  <br>
  <%= link_to 'See Inventory', items_path %>
</div>

app/views/items/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Inventory</h1>

  <%# Testing google oauth %>
  <div id="loggedInAlert" class="alert alert-info mb-4" role="alert">
    <p>You're logged in! Welcome to the Admin Item Dashboard!</p>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-warning text-white" %>
  </div>

  <!-- Search functionality -->

  <div class="d-flex mb-4">
    <%= link_to "Add Item", new_item_path, class: "btn btn-primary me-2 text-white" %>
    <%= link_to "View Member Items", member_items_path, class: "btn btn-secondary text-white" %>
  </div>

  <%= form_tag import_items_path, multipart: true, class: "mb-4" do %>
    <div class="mb-3">
      <%= file_field_tag :file, class: "form-control" %>
    </div>
    <%= submit_tag "Import", class: "btn btn-success me-2 text-white" %>
    <%= link_to 'Export Items', items_export_path, class: "btn btn-info text-white" %>
  <% end %>

 <table id="inventory-table" class="table">
    <thead>
      <tr>
        <th>Name</th>
        <% if current_user.admin? %>
          <th>Serial Number</th>
          <th>Internal ID</th>
          <th>Available?</th>
        <% end %>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr id="<%= dom_id(item) %>">
          <td><%= item.name %></td>
            <td><%= item.serial_number %></td>
            <td><%= item.id %></td>
            <td><%= item.available ? 'Yes' : 'No' %></td>
          <td>
            <%= link_to "Edit", edit_item_path(item), class: "btn btn-info btn-sm text-white" %>
            <%= link_to "Delete", item_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm text-white" %>
            <%= link_to 'Checkout', checkout_item_path(item), method: :put, class: "btn btn-success btn-sm text-white" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/member_items.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Inventory</h1>

  <div id="loggedInAlert" class="alert alert-info mb-4" role="alert">
    <p>You're logged in!</p>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-warning text-white" %>
  </div>

  <div class="mb-4">
    <%= form_tag(member_items_path, method: :get, class: "form-inline justify-content-center") do %>
      <div class="input-group mb-3">
        <%= text_field_tag :search, params[:search], placeholder: "Enter item name", class: "form-control mr-2", aria: { label: 'Search' } %>
        <%= submit_tag "Search", class: "btn btn-outline-secondary", style: "margin-left: 8px;" %>
      </div>
    <% end %>
  </div>


  <div class="row">
    <% @items.each do |item| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100"> <!-- make sure card height is consistent -->
          <div class="card-header">
            <%= item.name %>
          </div>
          <div class="card-body text-center">
            <p class="mt-3"><%= item.description %></p> <!-- Description added here -->
            <% if item.image.attached? %>
              <%= image_tag item.image, class: "img-fluid mx-auto d-block" %>
            <% else %>
              <%= image_tag "placeholder.png", class: "img-fluid mx-auto d-block" %> <!-- Updated placeholder image class -->
            <% end %>
          </div>
          <div class="card-footer text-center">
            <%= link_to "Show", item, class: "btn btn-primary btn-sm text-white" %>
            <%= link_to 'Checkout', checkout_item_path(item), method: :put, class: "btn btn-success btn-sm text-white" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1>New Item</h1>
  <%= render "form", item: @item %>
  <br>
  <div>
    <%= link_to "Back to inventory", items_path %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <h1>Item Details</h1>

  <%= render @item %>
  <strong>Description:</strong>
  <%= @item.description %>

  <div>
    <%= link_to "Edit this item", edit_item_path(@item) %>
    |
    <%= link_to "Delete this item", delete_item_path(@item) %>
    |
    <%= link_to "Back to items", items_path %>
  </div>
</div>