config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :maintenance_items
  # if user is not an admin, going to /admins will give 404 error
  authenticated :user, -> (user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/users'
    get 'admin/transactions'
    patch 'admin/users/:id', to: 'admin#update', as: 'admin/user'
    get 'items/index', as: :admin_items
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # root to: "items#index"
  root to: 'items#member_items'

  put 'items/:id/checkout', to: 'items#checkout', as: 'checkout_item'

  get '/items/export', to:'items#export'
  post 'items/import', to: 'items#import', as: 'import_items'

  resources :items, except: [:index] do
    member do
      get :delete
      put 'checkout'
      get 'checkout'
      #post :button_action
    end
  end

  put 'transactions/:id/approve', to: 'transactions#approve', as: 'approve_transaction'

  resources :transactions do
    member do
      get :delete
      put 'approve'
      get 'approve'
    end
  end

  get 'member-items', to: 'items#member_items'
  get 'transactions', to: 'transactions#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
    def index
      @transactions = Transaction.all
    end
  
    def show
      @transaction = Transaction.find(params[:id])
    end
  
    def new
      @transaction = Transaction.new()
    end
  
    def edit
    end
  
    def create
      @transaction = Transaction.new(transaction_params)
      @transaction.approved = false

      if Transaction.count != 0
        count = Transaction.last.id + 1
        @transaction.id = count
      else
        @transaction.id = 1
      end
      
      respond_to do |format|
        if @transaction.save
          format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
          format.json { render :show, status: :created, location: @transaction }
          #call mailer
          UserMailer.with(user: @transaction.email, item: @transaction.serial_number).checkout_email.deliver_later
          flash[:notice] = "Successfully created transaction"
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
    end

  
    def delete
      @transaction = Transaction.find(params[:id])
    end
  
    def destroy
      @transaction = Transaction.find(params[:id])
      @transaction.destroy
  
      respond_to do |format|
        format.html { redirect_to transactions_url, notice: "Transaction was successfully removed." }
        format.json { head :no_content }
      end
    end

    def approve
      @transaction = Transaction.find(params[:id])
    
      redirect_to transactions_path, notice: "Transaction was approved."
    end
  
    private
      def transaction_params 
        params.require(:transaction).permit(:email, :serial_number)
      end
  end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
    <%= form.label :serial_number,  style: "display: block"%>
    <%= form.text_field :serial_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Transaction Email:</strong>
    <%= transaction.email %>
    <strong>Serial Number:</strong>
    <%= transaction.serial_number %>
  </p>

</div>

app/views/transactions/delete.html.erb
<%= link_to("Back to Inventory", transactions_path, class: 'back-link') %>

<div class="transactions delete">
  <h2>Delete Transaction</h2>

  <%= form_for(@transaction, method: 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this transaction?</p>
    <p><%= @transaction.email %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Transaction") %>
    </div>

  <% end %>
</div>

app/views/transactions/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

app/views/transactions/index.html.erb
<div class="container">
  <h1>Transactions</h1>

  <div id="transactions">
    <% @transactions.each do |transaction| %>
      <%= render transaction %>
      <p>
        <%= link_to "Show", transaction %>
        <%= link_to "Edit", edit_transaction_path(transaction) %>
        <%= link_to "Delete", delete_transaction_path(transaction) %>
        <%= link_to 'Approve', approve_transaction_path(transaction), method: :put, class: "button" %>
      </p>
    <% end %>
  </div>

  <%= link_to "Add Transaction", new_transaction_path %>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to inventory", transactions_path %>
</div>

app/views/transactions/show.html.erb
<h1>Transaction Details</h1>

<%= render @transaction %>



<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Delete this transaction", delete_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>