config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :maintenance_items
  # if user is not an admin, going to /admins will give 404 error
  authenticated :user, -> (user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/users'
    get 'admin/transactions'
    patch 'admin/users/:id', to: 'admin#update', as: 'admin/user'
    get 'items/index', as: :admin_items
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # root to: "items#index"
  root to: 'items#member_items'

  put 'items/:id/checkout', to: 'items#checkout', as: 'checkout_item'

  get '/items/export', to:'items#export'
  post 'items/import', to: 'items#import', as: 'import_items'

  resources :items, except: [:index] do
    member do
      get :delete
      put 'checkout'
      get 'checkout'
      #post :button_action
    end
  end

  put 'transactions/:id/approve', to: 'transactions#approve', as: 'approve_transaction'

  resources :transactions do
    member do
      get :delete
      put 'approve'
      get 'approve'
    end
  end

  get 'member-items', to: 'items#member_items'
  get 'transactions', to: 'transactions#index'
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="flash__success"><%= notice %></p>
<% elsif alert %>
  <p class="flash__alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "W5AC App", root_path, class: "navbar-brand" %>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        <%# </li> %>
        <% if current_user %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Admin Inventory", admin_items_path, class: "nav-link" %>
            </li>
          <% end %>
        <% end %>
        <li class="nav-item">
          <%= link_to "Member Inventory", member_items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Maintenance Inventory", maintenance_items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Transactions", transactions_path, class: 'nav-link' %>
       </li>
       <% if current_user && current_user.role == 'Admin' %>
          <li class="nav-item">
            <%= link_to "Admin Dashboard", admin_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <%= render 'users/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuildBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    >
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'custom' %>

    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar'%>
      <%= render 'layouts/alerts' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/original_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuildBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>